
apiVersion: v1
kind: Pod
metadata:
 name: cmd-pod
 labels:
   purpose: demonstrate-command
spec:
  containers:
  - name: cmd-container
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
